# Generated by Django 2.2.7 on 2019-11-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=25)),
                ('bio', models.TextField(max_length=250)),
                ('links', models.CharField(max_length=255)),
            ],
        ),
    ]
